### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by reederda** [Shnatsel/furaffinity-dl#1]
FA's new "ReCaptcha" authentication is preventing the program from logging in properly to download files.

**Comment by Shnatsel** [comment]
Options I can think of that could work around that:

1. Dump cookies from a web browser and reuse those

1. Extract the captcha from the page and let the user solve it. This is how e.g. Reddit API does things, but decoupling ReCaptcha from the page would be tricky.

1. Run a specialized browser instance and collect the cookies set for it after the user logs in

**Comment by Shnatsel** [comment]
I have implemented loading cookies dumped from a web browser - it seemed like the sane option in this case. 

It unfortunately requires installing a (tiny) browser extension and is not as straightforward as simply entering your username and password. On the bright side, it no longer requires you to enter your password every time you're downloading a gallery, and it warns you when the login has failed.

I have also updated the README accordingly. If you run into any issues with this, please let me know.
