### ISSUE TITLE
Unable to use cookies

### ISSUE THREAD

**Issue by Helix-9** [Shnatsel/furaffinity-dl#10]
I am unsure why I can't use my cookies, if I don't use it I can download a library without issue, but when I include it I seem to get this

> --2018-06-24 19:02:35--  ftp://http/
           => ‘.listing’
Resolving http (http)... failed: Name or service not known.
wget: unable to resolve host address ‘http’

**Comment by Helix-9** [comment]
huh, this is embarrassing
I have now figured that a closed issue thread exist... and this issue is also there.... sooooooooo.... mistakes has been made and issue resolved
~~please don't kill me~~

**Comment by Shnatsel** [comment]
No worries, I don't bite.

Is there a different skin when you're logged in you're using compared to the default? I had reports of this script malfunctioning exactly like that with some FA skins (see #9) but I actually don't know what they are or how to switch them.

**Comment by Shnatsel** [comment]
Ah, found it in account settings. Seems to be a problem with the beta skin. If you switch back to classic you will be able to download even with cookies.

**Comment by Shnatsel** [comment]
I have just pushed an update that should fix it for you. Please download the new version and see if it works.

**Comment by Helix-9** [comment]
It worked on my main account! Thanks
