### ISSUE TITLE
Exported cookies.txt using ganbo, furaffinity-dl still doesn't like it.

### ISSUE THREAD

**Issue by eggmanstudio** [Shnatsel/furaffinity-dl#12]
I'm using Bash for Windows and when trying to use my cookies exported from Firefox using Ganbo (Yes, I was on the right tab, I checked), it still doesn't like them.

**Comment by Shnatsel** [comment]
If you have exported them on Windows, they may be in a Windows character
encoding and/or with weird Windows line endings.

See if `cat` command can display the file correctly. If not, use some kind
of converter from Windows encoding to proper UTF-8 and to Unix line endings.

**Comment by Shnatsel** [comment]
The encoding may have been changed depending on the exact way you've copied
the file.

Try running the script in an Ubuntu VM and copying the images.

чт, 8 нояб. 2018 г. в 21:27, eggmanstudio <notifications@github.com>:

**Comment by eggmanstudio** [comment]
All seems to be working in the VM.
I'll do my BASHing in actual Linux from now on methinks
