### ISSUE TITLE
Certificate not trusted

### ISSUE THREAD

**Issue by nar001** [Shnatsel/furaffinity-dl#14]
So I tried to use it to download a gallery, cookie file doesn't return anything bad but it stops when it says: 
ERROR: The certificate of ‘www.furaffinity.net’ is not trusted.
ERROR: The certificate of ‘www.furaffinity.net’ hasn't got a known issuer.
Which stops the download. How can I whitelist the certificate? Thanks!

**Comment by Shnatsel** [comment]
That's weird. What operating system are you using? 
Also, please post the output of the following command: `wget --verbose https://www.furaffinity.net`

**Comment by nar001** [comment]
I'm using Win 10 with Gnu subsystem thing and Debian installed

Also output:
--2019-02-28 21:05:26--  https://www.furaffinity.net/
Resolving www.furaffinity.net (www.furaffinity.net)... 2606:4700:10::6814:453b, 2606:4700:10::6814:463b, 104.20.69.59, ...
Connecting to www.furaffinity.net (www.furaffinity.net)|2606:4700:10::6814:453b|:443... connected.
ERROR: The certificate of ‘www.furaffinity.net’ is not trusted.
ERROR: The certificate of ‘www.furaffinity.net’ hasn't got a known issuer.

**Comment by Shnatsel** [comment]
Most likely something is intercepting your HTTPS connection and substituting the HTTPS certificate. Open the page in Firefox and compare the issuer and fingerprints with these:

![screenshot from 2019-02-28 21-27-05](https://user-images.githubusercontent.com/291257/53596433-00753c00-3ba0-11e9-96bc-e86ca7cddd38.png)

If you see something different, then something is trying to listen in on the connection and Debian is correct in rejecting it.

**Comment by nar001** [comment]
Seems to be the same thing isn't it?
![image](https://user-images.githubusercontent.com/15905072/53597633-95753680-3b9a-11e9-8e07-3ffd11791bce.png)

**Comment by Shnatsel** [comment]
This is weird. Okay, try this:
```shell
sudo apt-get update
sudo apt-get install ca-certificates
```
Other than that, I'm out of ideas.

**Comment by nar001** [comment]
It seems to have worked! Sorry for the trouble, I guess it doesn't install ca-certificates by default huh.
I assume it's by default when you install any distro?

**Comment by Shnatsel** [comment]
Yes, real distros always have it installed by default.
