### ISSUE TITLE
command not found when executing

### ISSUE THREAD

**Issue by dundundunnn** [Shnatsel/furaffinity-dl#16]
Okay so im new to this whole running script thing, ive installed wget, coreutils in ubuntu and updated my binaries, but i cant seem to download all it says is command not found

**Comment by Shnatsel** [comment]
Please run the following commands in console and post the full output:
```bash
mkdir test
cd test
git clone https://github.com/Shnatsel/furaffinity-dl.git
furaffinity-dl/furaffinity-dl scraps/---
```

**Comment by dundundunnn** [comment]
omg thanks so much, btw how do you use cookies, i downloaded the extension but it shows cannot open cookies file no such file or directory, you have provided cookies file but it does not contain valid cookies

**Comment by dundundunnn** [comment]
dundundunnn@DESKTOP-H0BMTU7:~/test$ furaffinity-dl/furaffinity-dl gallery/chisasa cookies.txt
Cannot open cookies file ‘cookies.txt’: No such file or directory
--2019-03-23 18:25:49--  https://www.furaffinity.net/gallery/chisasa
Resolving www.furaffinity.net (www.furaffinity.net)... 104.20.70.59, 104.20.69.59, 2606:4700:10::6814:463b, ...
Connecting to www.furaffinity.net (www.furaffinity.net)|104.20.70.59|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/home/dundundunnn/.cache/furaffinity-dl/fa-dl.zfq2GwhAps’

/home/dundundunnn/.cache/fura     [ <=>                                             ]  43.25K  --.-KB/s    in 0.07s

2019-03-23 18:25:50 (594 KB/s) - ‘/home/dundundunnn/.cache/furaffinity-dl/fa-dl.zfq2GwhAps’ saved [44293]

--------------

ERROR: You have provided a cookies file, but it does not contain valid cookies.

If this file used to work, this means that the cookies have expired;
you will have to log in to FurAffinity from your web browser and export the cookies again.

If this is the first time you're trying to use cookies, make sure you have exported them
in Netscape format (this is normally done through "cookie export" browser extensions)
and supplied the correct path to the cookies.txt file to this script.

If that doesn't resolve the issue, please report the problem at
https://github.com/Shnatsel/furaffinity-dl/issues

**Comment by Shnatsel** [comment]
Looks like you need a primer on how paths in Linux work.

You have a home directory where you normally have a bunch of folders such as "Music", "Downloads", etc. When you want to refer to to your home directory from the command line, you can do so by typing `~`. Directories are separated with slashes, so if you want to refer to the "Downloads" folder in your home directory, you'd type `~/Downloads`

There is also a concept of current directory in the shell. You can type `ls` to list all the files in the current directory; most programs operate on it by default, as does `furaffinity-dl`. It defaults to your home directory, but you can navigate to other places by using `cd` command.

So what you probably want to run to use furaffinity-dl something like:
```bash
mkdir chisasa
cd chisasa
~/furaffinity-dl/furaffinity-dl gallery/chisasa ~/Downloads/cookies.txt
```

**Comment by dundundunnn** [comment]
sorry im new to this, It returned as, 
-bash: /home/dundundunnn/furaffinity-dl/furaffinity-dl: No such file or directory

**Comment by Shnatsel** [comment]
Put whatever path you've used to download furaffinity-dl in there. Or just `git clone` into the home directory all over again.

**Comment by dundundunnn** [comment]
Oh I get what you mean now, when i renamed the folder from the file explorer ubuntu didnt update it so thats why, instead i restarted ubuntu, also i get permission denied when using furaffinity-dl from the home folder, i used from the test folder instead. thanks for everything though

**Comment by Shnatsel** [comment]
It seems it's working for you now, so I'm closing the issue.
