### ISSUE TITLE
BSD mktemp unsupported argument

### ISSUE THREAD

**Issue by Forst** [Shnatsel/furaffinity-dl#2]
The following piece of code does not work on the BSD version of `mktemp`:

```shell
mktemp --tmpdir=$runtime_dir
```

Fixed locally like this:

```shell
mktemp $runtime_dir/fdl.XXXXXX
```

Man page can be viewed [here](http://www.unix.com/man-page/FreeBSD/1/mktemp/).

**Comment by Shnatsel** [comment]
Fixed by 39c967617001dcc6a6754a2f0f027c01fc170971

Thanks!
