### ISSUE TITLE
Beta skin not supported

### ISSUE THREAD

**Issue by teleportingtortoise** [Shnatsel/furaffinity-dl#9]
Mostly noticed this with audio posts, but it seems to throw an "ftp" before the http in the url and then the entire process comes to a stop

also had trouble saving stuff from fav galleries, it just seems to go in a loop without downloading anything other than the first page

great script btw, it's been really helpful outside of these couple of issues!

**Comment by Shnatsel** [comment]
Saving favs has been fixed in this fork: https://github.com/BlueLycan/furaffinity-dl

There are also behavioral changes in that commit, so I cannot integrate it as-is. But you can use it for now as a stop-gap measure.

**Comment by Shnatsel** [comment]
Link to a specific post where the FTP issue happens would be helpful

**Comment by teleportingtortoise** [comment]
One of the submissions it happened with is http://www.furaffinity.net/view/26904990/

I tried the fork and it runs for a little bit, but doesn't seem to download more than one image and gives grep errors with each submission (no such file or directory), and then ends saying ```Cannot write to [filename]``` and ```/home/[user]/[git repos]/furaffinity-dl/furaffinity-dl: line 105: failed_downloads.txt: Permission denied```.

Thank you for your time, it's really appreciated.

**Comment by Shnatsel** [comment]
Downloading favorites is now fixed. Sorry it took so long - thesis happened.

**Comment by Shnatsel** [comment]
I did not run into the specific issue with ftp:// you've described, it malfunctioned in a different way for me on the specified post. That is now fixed.

Please test the latest version and see if it works for you.

**Comment by teleportingtortoise** [comment]
It's all good, life is important.

Had to change to the classic skin or it gave the same issue with tacking "ftp" in front of image urls, but it seems to work now as long as I'm using that skin. Thank you!

**Comment by Shnatsel** [comment]
I didn't know there are skins now. How do I switch them?

**Comment by Shnatsel** [comment]
I've tweaked the script to work with FA beta template. Please check if this fixes the issue.

**Comment by Shnatsel** [comment]
It works for me on the beta skin, so I assume the issue has been fixed. Please reopen if that's not the case.
